### ISSUE TITLE
Skins don't work on local accounts

### ISSUE THREAD

**Issue by DerpWerp** [AfoninZ/MultiMC5-Cracked#102]
### Operating System

Windows

### Description of bug

Skins don't work on local accounts

https://user-images.githubusercontent.com/91960533/142341793-ccd0d1f5-8fc2-414a-8b15-6125be03ab37.mp4

### Steps to reproduce

Please fix this

### Suspected cause

Idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
If you want skins use ely.by it's free

**Comment by Slddev** [comment]
I'm pretty sure that skins currently don't apply for Local. If you want a skin. Use ely.by, they are free. Just sign up and add a skin.

**Comment by Slddev** [comment]
> If you want skins use ely.by it's free

XD We both said the same thing at the same time

**Comment by maximmasterr** [comment]
Currently skins are not avalible to local accounts, please register and ely.by account.
