### ISSUE TITLE
I'm crashing... again... this time on 1.17.1

### ISSUE THREAD

**Issue by yum13241** [AfoninZ/MultiMC5-Cracked#104]
Well, it seems that combatedit is the issue, but that's weird, considering that only when i added a particular mod from the fabulously optimized modpack, then the error happened. Here is the crash log: https://paste.ee/p/3rQJy.

**Comment by yum13241** [comment]
I will try reverting my modpack to a backed up ver I have.

**Comment by Samisafool** [comment]
SMH this issue tracker is not for helping people with minecraft crashes, It's about helping people with launcher issues. Btw, there is a newer version of the launcher, update to it. (rename multimc.cfg to ultimmc.cfg)

**Comment by yum13241** [comment]
ik, and when i do that, ultimmc wont start, so i had to only copy folders that didnt exist.

**Comment by Samisafool** [comment]
duhh, that's in the readme

**Comment by yum13241** [comment]
well, trying to restore again, it turned out that i have to move the instance out, just so that its a fresh copy of the backup, now all thats left is to pray...

**Comment by yum13241** [comment]
Finally, I KNEW it wasn't combatedit! Thank god for backups.
