### ISSUE TITLE
Universal Build and native libraries. 

### ISSUE THREAD

**Issue by imabhaysutar** [AfoninZ/MultiMC5-Cracked#105]
### Role

I play vanilla and modded minecraft.

### Suggestion

One click way to get and config libraries required to run MC on M1 Natively 

### Benefit

Saves the trouble and errors on user part, better performance OTB.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Arm Macs aren't going anywhere, currently we need to add script and libraries from https://github.com/r58Playz/m1-multimc-hack or similar repos. A solution would be to package all libraries and provide them through updater for clients that require them. 

Also a native arm64 build of the launcher.

**Comment by Samisafool** [comment]
This is a light fork of MultiMC for cracked accounts, suggestions should be on MultiMC tracker. I don't recommend asking there though, they are definitely working on it.

**Comment by imabhaysutar** [comment]
Appreciate the response. 

MultiMC won't it as long as "Mojang do not support ARM systems and consequently neither do we."

So we have to wait I guess. 

Also the new build has blank icons on macOS, is that intentional? Is someone working on redesigning as part of rebrand?

Thanks.

**Comment by Samisafool** [comment]
It shouldn't have blank icons, you can check the icon in

https://github.com/AfoninZ/MultiMC5-Cracked/blob/develop/notsecrets/Launcher.ico

and

https://github.com/AfoninZ/MultiMC5-Cracked/blob/develop/notsecrets/logo.svg

**Comment by imabhaysutar** [comment]
It does for me, unsure why. 
 Thanks will check then out : )

**Comment by imabhaysutar** [comment]
@Samisafool I would like to contribute icon for this project. This is what I came up with for now, let me know how this feels, I want to send in a PR but right now the build makes icon files from a svg, unsure how I can add icons files directly. Thanks : )
![UltimMCrgb](https://user-images.githubusercontent.com/53598402/142720653-07f0a721-6e76-4296-8bbb-37531f38ff9f.png)

**Comment by Samisafool** [comment]
> @Samisafool I would like to contribute icon for this project. This is what I came up with for now, let me know how this feels, I want to send in a PR but right now the build makes icon files from a svg, unsure how I can add icons files directly. Thanks : ) ![UltimMCrgb](https://user-images.githubusercontent.com/53598402/142720653-07f0a721-6e76-4296-8bbb-37531f38ff9f.png)

There is a genicons.sh script (mac and linux) that generates the svg from pngs. It needs inkscape, png2icns, and the logo as 16x, 24x, 32x, 48x, 64x, and 128x png files.

**Comment by imabhaysutar** [comment]
So source should be pngs right?

**Comment by Samisafool** [comment]
yep.

**Comment by Samisafool** [comment]
they should be in the notsecrets folder, titled logo_(resolution).png

**Comment by imabhaysutar** [comment]
Can't I directly provide ico, incs, and svg? that's what ultimately gets used?

**Comment by Samisafool** [comment]
I suppose you could.

**Comment by imabhaysutar** [comment]
Cool, will do that. : )

**Comment by imabhaysutar** [comment]
https://github.com/imabhaysutar/MultiMC5-Cracked/tree/feature/newicon , what branch do I PR in? @Samisafool

**Comment by Samisafool** [comment]
PR in develop

**Comment by Samisafool** [comment]
You included a png, it should be svg

**Comment by imabhaysutar** [comment]
I have added it, it is flatten tho, please test it once.

**Comment by Samisafool** [comment]
.ico looks pixelated

**Comment by Samisafool** [comment]
so does the icns, also please remove the png

**Comment by imabhaysutar** [comment]
oof, I will try and fix that.

**Comment by Samisafool** [comment]
Let's talk further in #106

**Comment by maximmasterr** [comment]
We **should try** to support m1

**Comment by Sebastian-byte** [comment]
> 

Not really, remember that this is a light fork, I think the best solution is to wait until Mojang adds support for M1 and create an issue in the upstream repository.
