### ISSUE TITLE
Bitdefender antivirus marks app as a virus

### ISSUE THREAD

**Issue by tristanzwart** [AfoninZ/MultiMC5-Cracked#115]
### Operating System

Windows

### Description of bug

If I start it bitdefender maks it as dangerous and deletes the files. Whilst it shouldn't because there isn't a virus in it. So why is it doing this.

### Steps to reproduce

Install the latest version of bitdefender on windows and start the exe and wait for it to detect that it is malicious.

### Suspected cause

There is a virus in the exe or a different peace that could be flagged as malicious

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
Interesting. What is the virus?

**Comment by Samisafool** [comment]
Also try normal multimc.

**Comment by RDKRACZ** [comment]
Checked both zip and the exe with virustotal and nothing.
https://www.virustotal.com/gui/file/1e80d99983596d2a0d59ad443a5056aff91d6a28a89f70f168ede628cbe90e1e/detection
https://www.virustotal.com/gui/file/f28257f3d70fd0b4752994a4a27992964910bc6ff6d6fb70cd438cd09b1d5d71

Did you download it from the nightly link in the readme? Are you sure it was the UltimMC.exe that was flagged and not ex. fabric loader exe?

**Comment by tristanzwart** [comment]
It didn't tell me what it detected an I used the link in the readme. Also I definitely flagged the exe and also some other files. Also when I first installed it it didn't complain but now it does. So it could be a bug in bitdefender but I'm unsure

**Comment by tristanzwart** [comment]
> Also try normal multimc.

Normal multimc just works fine it does not say anything about it

**Comment by tristanzwart** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/63745203/144262474-32255de6-4b24-41a3-893b-15544c1e9031.png)

**Comment by AndreVuillemot160** [comment]
I think some kind of digital signature, will help. With this signature you can tell bitdefender to shut up.

**Comment by sinanisler** [comment]
just mark it as false positive and let bitdefender know. there isnt any malware...

**Comment by tristanzwart** [comment]
> just mark it as false positive and let bitdefender know. there isnt any malware...

I am not administration on that device so I can't do that.

**Comment by tristanzwart** [comment]
> I think some kind of digital signature, will help. With this signature you can tell bitdefender to shut up.

How can you do this? I know some stuf about programming but I am not an expert

**Comment by AndreVuillemot160** [comment]
We can actually submit here https://www.bitdefender.com/consumer/support/answer/29358/
That this file is not virus lol.

**Comment by tristanzwart** [comment]
> We can actually submit here https://www.bitdefender.com/consumer/support/answer/29358/ That this file is not virus lol.

Thanks for the info i submitted It.

**Comment by AndreVuillemot160** [comment]
Any news?

**Comment by tristanzwart** [comment]
> Any news?

Well I got a confirmation email from bitdefender and if it's not a virus it will be removed via signature update. I haven't heard from them after that also haven't tested so I don't know. I can maybe test it later today

**Comment by tristanzwart** [comment]
It seems to be working now I am going to test it some more and then I will close the isue

**Comment by tristanzwart** [comment]
It seems that everything works now so I am closing its issue thanks for the help everyone.
