### ISSUE TITLE
Minecraft not launching with Java 17

### ISSUE THREAD

**Issue by Den4enko** [AfoninZ/MultiMC5-Cracked#121]
### Operating System

Windows

### Description of bug
When i launch minecraft. Launcher shuts down.
Log:

 1.573 D Probing the following Java paths: 
    1.573 D   "C:/Program Files/Java/jre8/bin/javaw.exe"
    1.573 D   "C:/Program Files/Java/jre7/bin/javaw.exe"
    1.573 D   "C:/Program Files/Java/jre6/bin/javaw.exe"
    1.573 D   "C:/Program Files/BellSoft/LibericaJDK-17/bin/javaw.exe"
    1.573 D   "C:/Program Files (x86)/Java/jre8/bin/javaw.exe"
    1.573 D   "C:/Program Files (x86)/Java/jre7/bin/javaw.exe"
    1.573 D   "C:/Program Files (x86)/Java/jre6/bin/javaw.exe"
    1.573 D   "javaw"
    1.573 D Task "JavaCheckerJob(0x43008e0)" starting for the first time
    1.573 D "Java detection"  started.
    1.573 D Env: ignoring "JAVA_HOME" "C:\\Program Files\\BellSoft\\LibericaJDK-17\\"
    1.573 D "Running java checker: C:/Program Files/Java/jre8/bin/javaw.exe-jar C:/Users/dimad/Desktop/UltimMC/jars/JavaCheck.jar"
    1.574 D Java checker has failed to start.
    1.574 D Process environment:
    1.574 D ("OneDriveConsumer=C:\\Users\\dimad\\OneDrive", "PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD", "PROCESSOR_LEVEL=23", "PROCESSOR_ARCHITEW6432=AMD64", "ALLUSERSPROFILE=C:\\ProgramData", "GOPATH=C:\\Users\\dimad\\go", "PROCESSOR_REVISION=7100", "OS=Windows_NT", "windir=C:\\WINDOWS", "ProgramFiles(x86)=C:\\Program Files (x86)", "NUMBER_OF_PROCESSORS=12", "=::=::\\", "LOCALAPPDATA=C:\\Users\\dimad\\AppData\\Local", "USERNAME=dimad", "TEMP=C:\\Users\\dimad\\AppData\\Roaming\\TEMP", "HOMEPATH=\\Users\\dimad", "USERPROFILE=C:\\Users\\dimad", "CommonProgramFiles=C:\\Program Files (x86)\\Common Files", "PROCESSOR_ARCHITECTURE=x86", "ComSpec=C:\\WINDOWS\\system32\\cmd.exe", "SESSIONNAME=Console", "TMP=C:\\Users\\dimad\\AppData\\Roaming\\TEMP", "ProgramData=C:\\ProgramData", "VBOX_HWVIRTEX_IGNORE_SVM_IN_USE=1", "APPDATA=C:\\Users\\dimad\\AppData\\Roaming", "ProgramW6432=C:\\Program Files", "CommonProgramW6432=C:\\Program Files\\Common Files", "DriverData=C:\\Windows\\System32\\Drivers\\DriverData", "IntelliJ IDEA Community Edition=C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.2.3\\bin;", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "SystemDrive=C:", "SystemRoot=C:\\WINDOWS", "HOMEDRIVE=C:", "USERDOMAIN=DIMA-PC", "Path=C:\\Program Files\\BellSoft\\LibericaJDK-17\\bin\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Go\\bin;C:\\Users\\dimad\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\dimad\\AppData\\Local\\GitHubDesktop\\bin;;C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.2.3\\bin;;C:\\Users\\dimad\\go\\bin", "PUBLIC=C:\\Users\\Public", "USERDOMAIN_ROAMINGPROFILE=DIMA-PC", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "OneDrive=C:\\Users\\dimad\\OneDrive", "LOGONSERVER=\\\\DIMA-PC", "ProgramFiles=C:\\Program Files (x86)", "COMPUTERNAME=DIMA-PC", "PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules")
    1.574 D Native environment:
    1.574 D ("OneDriveConsumer=C:\\Users\\dimad\\OneDrive", "PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD", "PROCESSOR_LEVEL=23", "PROCESSOR_ARCHITEW6432=AMD64", "ALLUSERSPROFILE=C:\\ProgramData", "GOPATH=C:\\Users\\dimad\\go", "PROCESSOR_REVISION=7100", "OS=Windows_NT", "windir=C:\\WINDOWS", "ProgramFiles(x86)=C:\\Program Files (x86)", "NUMBER_OF_PROCESSORS=12", "=::=::\\", "LOCALAPPDATA=C:\\Users\\dimad\\AppData\\Local", "USERNAME=dimad", "TEMP=C:\\Users\\dimad\\AppData\\Roaming\\TEMP", "HOMEPATH=\\Users\\dimad", "USERPROFILE=C:\\Users\\dimad", "JAVA_HOME=C:\\Program Files\\BellSoft\\LibericaJDK-17\\", "CommonProgramFiles=C:\\Program Files (x86)\\Common Files", "PROCESSOR_ARCHITECTURE=x86", "ComSpec=C:\\WINDOWS\\system32\\cmd.exe", "SESSIONNAME=Console", "ProgramData=C:\\ProgramData", "TMP=C:\\Users\\dimad\\AppData\\Roaming\\TEMP", "VBOX_HWVIRTEX_IGNORE_SVM_IN_USE=1", "APPDATA=C:\\Users\\dimad\\AppData\\Roaming", "ProgramW6432=C:\\Program Files", "CommonProgramW6432=C:\\Program Files\\Common Files", "DriverData=C:\\Windows\\System32\\Drivers\\DriverData", "IntelliJ IDEA Community Edition=C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.2.3\\bin;", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "SystemDrive=C:", "SystemRoot=C:\\WINDOWS", "HOMEDRIVE=C:", "USERDOMAIN=DIMA-PC", "Path=C:\\Program Files\\BellSoft\\LibericaJDK-17\\bin\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Go\\bin;C:\\Users\\dimad\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\dimad\\AppData\\Local\\GitHubDesktop\\bin;;C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.2.3\\bin;;C:\\Users\\dimad\\go\\bin", "PUBLIC=C:\\Users\\Public", "USERDOMAIN_ROAMINGPROFILE=DIMA-PC", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "OneDrive=C:\\Users\\dimad\\OneDrive", "LOGONSERVER=\\\\DIMA-PC", "ProgramFiles=C:\\Program Files (x86)", "COMPUTERNAME=DIMA-PC", "PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules")
    1.574 D "Java detection" progress: 1 / 8
    1.574 D Env: ignoring "JAVA_HOME" "C:\\Program Files\\BellSoft\\LibericaJDK-17\\"
    1.574 D "Running java checker: C:/Program Files/Java/jre7/bin/javaw.exe-jar C:/Users/dimad/Desktop/UltimMC/jars/JavaCheck.jar"
    1.574 D Java checker has failed to start.
    1.574 D Process environment:
    1.574 D ("OneDriveConsumer=C:\\Users\\dimad\\OneDrive", "PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD", "PROCESSOR_LEVEL=23", "PROCESSOR_ARCHITEW6432=AMD64", "ALLUSERSPROFILE=C:\\ProgramData", "GOPATH=C:\\Users\\dimad\\go", "PROCESSOR_REVISION=7100", "OS=Windows_NT", "windir=C:\\WINDOWS", "ProgramFiles(x86)=C:\\Program Files (x86)", "NUMBER_OF_PROCESSORS=12", "=::=::\\", "LOCALAPPDATA=C:\\Users\\dimad\\AppData\\Local", "USERNAME=dimad", "TEMP=C:\\Users\\dimad\\AppData\\Roaming\\TEMP", "HOMEPATH=\\Users\\dimad", "USERPROFILE=C:\\Users\\dimad", "CommonProgramFiles=C:\\Program Files (x86)\\Common Files", "PROCESSOR_ARCHITECTURE=x86", "ComSpec=C:\\WINDOWS\\system32\\cmd.exe", "SESSIONNAME=Console", "TMP=C:\\Users\\dimad\\AppData\\Roaming\\TEMP", "ProgramData=C:\\ProgramData", "VBOX_HWVIRTEX_IGNORE_SVM_IN_USE=1", "APPDATA=C:\\Users\\dimad\\AppData\\Roaming", "ProgramW6432=C:\\Program Files", "CommonProgramW6432=C:\\Program Files\\Common Files", "DriverData=C:\\Windows\\System32\\Drivers\\DriverData", "IntelliJ IDEA Community Edition=C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.2.3\\bin;", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "SystemDrive=C:", "SystemRoot=C:\\WINDOWS", "HOMEDRIVE=C:", "USERDOMAIN=DIMA-PC", "Path=C:\\Program Files\\BellSoft\\LibericaJDK-17\\bin\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Go\\bin;C:\\Users\\dimad\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\dimad\\AppData\\Local\\GitHubDesktop\\bin;;C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.2.3\\bin;;C:\\Users\\dimad\\go\\bin", "PUBLIC=C:\\Users\\Public", "USERDOMAIN_ROAMINGPROFILE=DIMA-PC", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "OneDrive=C:\\Users\\dimad\\OneDrive", "LOGONSERVER=\\\\DIMA-PC", "ProgramFiles=C:\\Program Files (x86)", "COMPUTERNAME=DIMA-PC", "PSModulePath=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules")
    1.574 D Native environment:

### Steps to reproduce

1. Install this launcher
2. Install Java 17, or other(not 7).
3. Start Minecraft

### Suspected cause

I think the thing is in JavaChecker, he is checking the wrong version.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Den4enko** [comment]
> Show the java settings in launcher

![image](https://user-images.githubusercontent.com/60628208/144456654-546c81fd-02d4-4025-9909-13e99b22fcf5.png)

**Comment by Samisafool** [comment]
click auto-detect and select java 17

**Comment by Den4enko** [comment]
But original launcher doesn't have this issue

**Comment by Samisafool** [comment]
I can't replicate this issue, someone else should help

**Comment by Den4enko** [comment]
This issue fixed in new build! I closing issue!
