### ISSUE TITLE
App can't be opened in Mac (M1 )

### ISSUE THREAD

**Issue by ashinlaurel** [AfoninZ/MultiMC5-Cracked#124]
### Operating System

macOS

### Description of bug

<img width="263" alt="image" src="https://user-images.githubusercontent.com/44382446/144824670-01d227c6-a583-49c3-bffb-1f7d28334d7f.png">

The application cannot be opened in Mac OS Monterey running on MacBook Air M1.

### Steps to reproduce

Unzip the zip file and try to run it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
I think it's for intel ones only, try using rosella

**Comment by Jay59376** [comment]
> I think it's for intel ones only, try using rosella

bruh :(
The one that was here 5 months ago(The Previous one) worked so well with M1 mac mate :(

**Comment by Sebastian-byte** [comment]
You need to use `chmod +x /path/to/UltimMC.app/Contents/MacOS/UltimMC`, refer to #125
