### ISSUE TITLE
No OptiFine

### ISSUE THREAD

**Issue by josefv2** [AfoninZ/MultiMC5-Cracked#126]
Hi. The official optifine.net download doesn't work on cracked MC because it asks to open the official launcher at least once. For this reason, I cannot ask in the OptiFine page, since they don't support cracks.

The issue is there is no OptiFine at all for UltimMC, unlike TLauncher which allows you to easily select it, there is no Opti version at all. You can't choose any version that isn't vanilla and you can't add them manually either because the instances system only registers vanilla versions.

I would like to know how it's possible to implement it. Many thanks in advance for the reply.

**Comment by maximmasterr** [comment]
You can use forge to install optifine

**Comment by josefv2** [comment]
Thanks for replying. There is also an issue with that, and it's the "Install Forge" option is greyed out and impossible to select for my 1.18 instance. I tried to search the problem, but all the solutions point to installing from there.

**Comment by Sebastian-byte** [comment]
> 

This is an upstream issue, Forge install is broken, consider using Fabric + Sodium.
