### ISSUE TITLE
Shaders not appearing

### ISSUE THREAD

**Issue by josefv2** [AfoninZ/MultiMC5-Cracked#127]
I have managed to get the real OptiFine mod. I don't use Forge, I got the .jar mod and wanted to install it directly. So I ran the .jar, selected extract, and added .jar file to 1.18 instance. Now it appears as modded Minecraft as if it was running; however, the shaders option doesn't appear at all! I have many many installed, I have no idea why there is no shaders option anywhere.

Thanks.

**Comment by josefv2** [comment]
> [1.18.zip](https://github.com/AfoninZ/MultiMC5-Cracked/files/7681530/1.18.zip)
> 
> Download that, go on the launcher and click "Add Instance" then "Import from zip" then select this. And tell me if there is a problem or something.

Thank you so much!

Before closing, can I ask how you did it? For next update not having to ask again.

**Comment by Slddev** [comment]
> Before closing, can I ask how you did it? For next update not having to ask again, and do it myself.

If you open up the zip file you will see it contains the icon, `mmc-pack.json` and a `instance.cfg`. Those just contain information about the instance. 

To actually make it work we need to patch in Optifine into the instance. So if you look into the libraries folder, you will see the extracted Optifine jar and Optifine's own launch wrapper. With this in place we can make a patch. So we go in to patches folder and see `optifine.Optfine.json` and basically just make sure that the launcher knows to patch in the two libraries into Minecraft.

Alright, how to update it in the future?

1. Download the latest Optifine jar in their website.
2. Extract the jar. (Via pressing the "Extract" button)
3. Open the **downloaded** jar as a zip file (using 7Zip or WinRAR) and find the launch wrapper. (The name should be similar to `launchwrapper-of-2.X.jar` Extract the file.
4. Now update the files in the libraries. Using the **extracted** Optifine jar and the launch wrapper.
5. Now just check in all of the files if the names are correct.
6. Pack it into a zip and import it into UltimMC.

*P.S. Make sure you check the patch json file, mmc-pack, and the instance.cfg for names to be changed. Should be pretty self-explanatory.*

**Comment by Samisafool** [comment]
There is an easier way to do it, just add the extracted jar as a jarmod (In the section where you install fabric, there is an add button)

**Comment by Slddev** [comment]
> There is an easier way to do it, just add the extracted jar as a jarmod (In the section where you install fabric, there is an add button)

That's how he did it before but as he said, the shaders don't work for some reason.
