### ISSUE TITLE
Make a guide on how to install it for linux

### ISSUE THREAD

**Issue by Qpac-x** [AfoninZ/MultiMC5-Cracked#133]
### Role

makes playing cracked modpacks easiers

### Suggestion

Make a guide on how to get it working on linux

### Benefit

more unexperienced linux users can use it

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

so basically im on zorin os lite 16 and im very new to linux and downloading the prebuilt linux version gives me a file that when extracts is basically useless as when i try running the application it opens the text editor can someone please tell if im doing something wrong and tell me the correct way

**Comment by Samisafool** [comment]
The guide is in the readme...
![image](https://user-images.githubusercontent.com/59611020/145676432-cc6914b0-9e71-4eb7-85d1-11ba17ca3f01.png)
