### ISSUE TITLE
Make Install Fails With Fatal Error

### ISSUE THREAD

**Issue by adikpb** [AfoninZ/MultiMC5-Cracked#135]
### Operating System

macOS

### Description of bug

Running `make Install` results in `fatal error: fatal error: 'flows/MojangRefresh.h' file not found`

![Screen Shot 2021-12-13 at 9 56 10 AM](https://user-images.githubusercontent.com/67222969/145760049-610aba32-a3d2-4e6b-bc25-a731fa5097a4.png)

![Screen Shot 2021-12-13 at 9 56 21 AM](https://user-images.githubusercontent.com/67222969/145760052-1b87af9e-d3df-4438-b5ed-40e2b7e86324.png)

### Steps to reproduce

Run `make install` after installing qt5.12 instead of qt5.6

### Suspected cause

Missing files in `launcher/minecraft/auth/flows/`

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
Yeah, you have to remove a few lines from `launcher/CMakelists.txt`, that include "flows/MojangRefresh.h"

Be careful though, it doesn't let you login. A few things are broken right now.

**Comment by adikpb** [comment]
I didnt find it in the cmakelists but i did find it in a cpp, i removed that particular line from there. I am now facing a new error :
```
MultiMC5-Cracked/launcher/minecraft/auth/Yggdrasil.cpp:213:9: error: use of undeclared identifier 'yggdrasilProfile'
        yggdrasilProfile = responseData.value("selectedProfile").toObject();
        ^
1 error generated.
make[2]: *** [launcher/CMakeFiles/Launcher_logic.dir/minecraft/auth/Yggdrasil.cpp.o] Error 1
make[1]: *** [launcher/CMakeFiles/Launcher_logic.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Samisafool** [comment]
Oh yes, it was in a cpp file my bad. Someone will fix these soon, but for now why not use the normal build?

**Comment by adikpb** [comment]
I tried accessing the normal build, but the link seems to be dead :,)

**Comment by Samisafool** [comment]
wdym? It works fine for me, just checked

**Comment by Samisafool** [comment]
Here's osx: https://nightly.link/AfoninZ/MultiMC5-Cracked/workflows/main/develop/mmc-cracked-osx64.zip

**Comment by adikpb** [comment]
Thank You So Much!

**Comment by adikpb** [comment]
![Screen Shot 2021-12-13 at 12 50 34 PM](https://user-images.githubusercontent.com/67222969/145780819-c9ca233c-2cfc-426f-a6f5-edb961ba804c.png)

**Comment by Samisafool** [comment]
Oh sorry didn't notice you sent this, anyway nightly.link works for me so try rebooting or using a vpn if you have one
Or check your firewall

**Comment by zippoking** [comment]
Any updates on a fix? I still get the "'flows/MojangRefresh.h' file not found"-error on Windows when cloning the current repository. Removing some lines in the .cpp file doesnt fix anything as i am getting new errors.

Would love to use the latest version. 

Thanks you so much in advance.
Best regards
Zippoking

**Comment by zippoking** [comment]
Update: after removing one more line i actually could build it.

However i have a new error:
![image](https://user-images.githubusercontent.com/18005338/146829550-7a1786e9-e39f-484e-b50b-b8e8d576cd82.png)

I can't even login on local. But i guess you already are aware of this issue?

Thanks again!

**Comment by R1413** [comment]
pain
