### ISSUE TITLE
Update after Fırst Install Problem

### ISSUE THREAD

**Issue by sinanisler** [AfoninZ/MultiMC5-Cracked#136]
### Role

update breaks the offline playing.  after first install when opening multimc first time if player makes the update multimc becomes premium multimc.

### Suggestion

update feature needs to completely removed or moved.

### Benefit

offline gameplay will work.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

this update problem people having this issue alot. it is just regular reflex for people to update to new software. but when they do update this offline-multimc they install the premium-multimc and they cant make offline account and they cant use the software at all.

i suggest just deleting this update so it doesnt suggest "new software update me" bs so people never see update at all.

here is the useless update thing in action.
screenshot: https://www.atarikafa.com/topluluk/assets/files/2021-12-14/1639495235-213090-resim.png

**Comment by Samisafool** [comment]
Please close this.

See #30
