### ISSUE TITLE
Latest release does not launch

### ISSUE THREAD

**Issue by RDKRACZ** [AfoninZ/MultiMC5-Cracked#138]
### Operating System

Linux

### Description of bug

**MultiMC does work**. Linux Deepin (Debian). Downloaded from the nighly link. This gets printed when trying to launch
```
No missing dependencies found.
/home/nacia/Desktop/mmc-stable-lin64/MultiMC/MultiMC: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/nacia/Desktop/mmc-stable-lin64/MultiMC/bin/libLauncher_nbt++.so)
/home/nacia/Desktop/mmc-stable-lin64/MultiMC/MultiMC: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/nacia/Desktop/mmc-stable-lin64/MultiMC/bin/libLauncher_rainbow.so)

```

### Steps to reproduce

Well, try to launch on a Debian-based system?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by maximmasterr** [comment]
Try updating system

**Comment by RDKRACZ** [comment]
It's up to date. I even added Debian backports repo

**Comment by person4268** [comment]
You'll need to compile it yourself probably, the builds probably aren't static.
