### ISSUE TITLE
Latest release does not launch (MacOS Monterey 12.0.1)

### ISSUE THREAD

**Issue by vrindarx** [AfoninZ/MultiMC5-Cracked#139]
### Operating System

macOS

### Description of bug

mmc-cracked-osx64.zip when extracted gives UltimMC.app... but it doesn't have an icon, I don't know if it is supposed to have one.

Moved that to the Applications folder and tried to launch it, even tried to **right click > open**.
It just says '**The application "UltimMC" can't be opened.**'

Even did **chmod +x UltimMC.app** in Applications folder. Didn't help.

### Steps to reproduce

Try running latest release on macOS monterey 12.0.1, but I don't know if it's universal.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by vrindarx** [comment]
Ok I opened the app, the issue was caused by Archive Utility.

Extracting the zip with **Unarchiver did the job**.

I read https://superuser.com/questions/1345755/how-to-fix-the-application-cant-be-opened-on-mac

**Comment by COOLMAXPRO** [comment]
> Ok I opened the app, the issue was caused by Archive Utility.
> 
> Extracting the zip with **Unarchiver did the job**.
> 
> I read https://superuser.com/questions/1345755/how-to-fix-the-application-cant-be-opened-on-mac

After opening the app with Unarchiver the app said its corrupt

**Comment by vrindarx** [comment]
Noob Suggestion: try downloading it again
