### ISSUE TITLE
UltimMC not launching even after I did chmod +x UltimMC

### ISSUE THREAD

**Issue by Vapstare1** [AfoninZ/MultiMC5-Cracked#140]
### Operating System

Linux

### Description of bug

When I did chmod +x UltimMC and tried to launch it for the first time it worked but when i tried the second time i saw a glimpse of the terminal opening and closing and nothing else happened

### Steps to reproduce

First extract the mmc-cracked-lin64.zip
Open the terminal and cd into mmc-cracked-lin64/UltimMC
Run chmod +x UltimMC
Run UltimMC as a program
Try to run it the second time

### Suspected cause

Idk I am a linux noob

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RDKRACZ** [comment]
Nobody will be able to help you if you don’t provide logs. Try running ultimmc from terminal and copy everything that got printed.

**Comment by Vapstare1** [comment]
Log:
Launcher Dir: /home/vapstare/Downloads/mmc-cracked-lin64/UltimMC
No missing dependencies found.
/home/vapstare/Downloads/mmc-cracked-lin64/UltimMC/UltimMC: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory

**Comment by Vapstare1** [comment]
Nevermind I installed qt5-base and the problem is now solved thx reminding me to run it from the terminal or would not have found the issue
