### ISSUE TITLE
A "Install Legacy Fabric" button.

### ISSUE THREAD

**Issue by yum13241** [AfoninZ/MultiMC5-Cracked#146]
### Role

I would like to play with Legacy Fabric on MultiMC.

### Suggestion

On applicable instances (<=1.13.2) allow the user to select the button, on newer versions, gray it out.

### Benefit

Because it would make playing Legacy Fabric easier. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Btw their website is here at https://bruh.legacyfabric.net.

I can see this being implemented in multiple ways.

Ungray the Install Fabric button and allow the user to select it, but download legacy fabric instead.

Make a new Install Legacy Fabric button that is grayed on 1.14+

**Comment by Slddev** [comment]
We do not add features to MultiMC other than making it viable to use with offline accounts. Make this issue upstream. Then if it gets added, UltimMC will update too.

**Comment by yum13241** [comment]
Got it.
