### ISSUE TITLE
The fix for not compiling.

### ISSUE THREAD

**Issue by JulekSTN** [AfoninZ/MultiMC5-Cracked#147]
Hi,

In the latest build, the error occuring there is also in the first 'non-building' version.
Here is the log from GitHub Actions:

`[ 18%] Building CXX object buildconfig/CMakeFiles/BuildConfig.dir/BuildConfig.cpp.obj
D:\a\MultiMC5-Cracked\MultiMC5-Cracked\build\buildconfig\BuildConfig.cpp: In constructor 'Config::Config()':
D:\a\MultiMC5-Cracked\MultiMC5-Cracked\build\buildconfig\BuildConfig.cpp:23:21: error: 'To' was not declared in this scope
     VERSION_BUILD = To;
                     ^
mingw32-make[2]: *** [buildconfig/CMakeFiles/BuildConfig.dir/BuildConfig.cpp.obj] Error 1
buildconfig\CMakeFiles\BuildConfig.dir\build.make:90: recipe for target 'buildconfig/CMakeFiles/BuildConfig.dir/BuildConfig.cpp.obj' failed
mingw32-make[1]: *** [buildconfig/CMakeFiles/BuildConfig.dir/all] Error 2
CMakeFiles\Makefile2:1358: recipe for target 'buildconfig/CMakeFiles/BuildConfig.dir/all' failed
mingw32-make[1]: *** Waiting for unfinished jobs....
[ 18%] Building CXX object libraries/katabasis/CMakeFiles/Katabasis.dir/src/JsonResponse.cpp.obj
[ 18%] Building CXX object libraries/katabasis/CMakeFiles/Katabasis.dir/src/PollServer.cpp.obj
[ 19%] Building CXX object libraries/katabasis/CMakeFiles/Katabasis.dir/src/Reply.cpp.obj
[ 19%] Linking CXX static library libKatabasis.a
[ 19%] Built target Katabasis
mingw32-make: *** [all] Error 2
makefile:144: recipe for target 'all' failed
Error: Process completed with exit code 2.`

There is something with the **VERSION_BUILD = To;** line in _BuildConfig.cpp:23:21_.
I bet you will know how to fix it.

I also have some other suggestions but i will submit other issues.

Kind regards,
JulekSTN

**Comment by Samisafool** [comment]
> VERSION_BUILD = To

This is because multimc stopped guest access to one of their servers. Sebastian-byte denied the fix because of a few reasons. local builds still work.

**Comment by Sebastian-byte** [comment]
Fixed.
