### ISSUE TITLE
Can't log in with Ely.By account.

### ISSUE THREAD

**Issue by literally-Zak** [AfoninZ/MultiMC5-Cracked#151]
### Operating System

Linux

### Description of bug

When trying to log in with an **Ely.By account**, it doesn't work.

![issueultimmc](https://user-images.githubusercontent.com/98234074/150652865-7ae3e1c9-1064-4e08-b9f8-15ab7afa40c3.png)

### Steps to reproduce

- Open UltimMC
- Add a new account with Ely.By

### Suspected cause

I don't know.

**Comment by J1Github** [comment]
I have the same issue on mac

**Comment by Ka1dz0** [comment]
Duplicate of #148
