### ISSUE TITLE
Error when unpacking the zip-archive with the game

### ISSUE THREAD

**Issue by jznav9ex** [AfoninZ/MultiMC5-Cracked#155]
### Operating System

Windows

### Description of bug

there is a "Data Error" error when trying to extract the "UltimMC.exe" file. The other files are extracted successfully. I'm using "7-zip" archiver

### Steps to reproduce

trying to extract the "UltimMC.exe" file

### Suspected cause

damaged archive or exe file?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
This is possibly a GitHub problem which causes downloads to get corrupted, already happened before, try downloading again.
