### ISSUE TITLE
Crashes hacks

### ISSUE THREAD

**Issue by GerroPogi** [AfoninZ/MultiMC5-Cracked#157]
### Role

Anarchy Minecrafter

### Suggestion

Stop crashing when using hacked clients

### Benefit

So I can use replay mod and also use MultiMC

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The crash log is
https://paste.ee/p/7R9j9
I used Replaymod, 3arth4ack, LeuxBackdoor, KamiBlue Optifine andRealtime translator

**Comment by Samisafool** [comment]
Unrelated to the launcher, it's optifine that's causing it.

**Comment by GerroPogi** [comment]
Doesn't work
https://paste.ee/p/y0fFP

**Comment by Samisafool** [comment]
Does normal minecraft work?

Yes: It's a mod problem
