### ISSUE TITLE
Current linux version from nightly link doesn't launch

### ISSUE THREAD

**Issue by RDKRACZ** [AfoninZ/MultiMC5-Cracked#158]
### Operating System

Linux

### Description of bug

Download Linux release from https://nightly.link/AfoninZ/MultiMC5-Cracked/workflows/main/develop.
Try to launch it

Get `./UltimMC: line 39: /home/nacia/Downloads/UltimMC/bin/UltimMC: No such file or directory`

### Steps to reproduce

Download Linux release from https://nightly.link/AfoninZ/MultiMC5-Cracked/workflows/main/develop.
Try to launch it

Get `./UltimMC: line 39: /home/nacia/Downloads/UltimMC/bin/UltimMC: No such file or directory`

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
You are in the bin folder. Try going 1 folder up

**Comment by RDKRACZ** [comment]
![image](https://user-images.githubusercontent.com/43277609/151392726-53023b97-aad0-4cb8-9c6e-6c8582212cdc.png)

**Comment by RDKRACZ** [comment]
I'm not entirely sure it's something with UltimMC as I have a similar problem with other app but that would mean there is something broken in the `bash` package

**Comment by Samisafool** [comment]
![image](https://user-images.githubusercontent.com/59611020/151393324-f08c0e75-9c98-48aa-82b5-be4acb0dbe4c.png)

Something on your end?

**Comment by RDKRACZ** [comment]
Other shells don't see the file too. I have no idea what's going on but it looks like it's really on my end.

**Comment by Samisafool** [comment]
Try re-unzipping the file @RDKRACZ ?

**Comment by RDKRACZ** [comment]
With the help of the author of https://github.com/Kron4ek/minecraft-vortex-launcher/ I now know that the issue is in the operating system itself https://nixos.wiki/wiki/Packaging/Binaries

**Comment by itslychee** [comment]
This may be helpful! https://github.com/itslychee/dotfiles/blob/nixos/packages/ultimmc.nix
