### ISSUE TITLE
no skin

### ISSUE THREAD

**Issue by horriblejoseph** [AfoninZ/MultiMC5-Cracked#162]
### Operating System

Windows

### Description of bug

For minecraft below 1.3 I look like the default skin.

### Steps to reproduce

make an instance of minecraft below 1.3
load it
create a world
wait for world to load
spawn

### Suspected cause

I supposed to my skin from ely.by

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Fatih120** [comment]
This is an issue with old versions of Minecraft regarding the fact that they would lookup a now-defunct server for skins that no longer exists. SkinPort exists for 1.7, but this is not a bug for UltimMC.

**Comment by horriblejoseph** [comment]
Thank you
