### ISSUE TITLE
Modpack Crashing/Instability

### ISSUE THREAD

**Issue by NekoTheWeird** [AfoninZ/MultiMC5-Cracked#164]
### Operating System

Linux

### Description of bug

**The majority of modpacks downloaded through the UltimMC launcher just simply dont work.** 

Either it throws an error the moment the Instance is opened:
https://pastebin.com/mSVTF9Fu

or when the Instance loads (Game reports a fatal error loading a mod/s)
https://pastebin.com/9Umr657L

_Linux distro: Garuda Linux Dragonized (Arch-Based)
Java version: Java 17 openJDK_

### Steps to reproduce

**Unsure.** Seemingly random, but not at all.

Sevtech : Ages (Modpack ver. 3.2.3) = Throws a Java error on startup.

All The Mods 1.16.5 (Modpack ver. 1.8.18) = Unable to load a critical mod.

Better Minecraft Fabric 1.18.1 = Loads correctly

### Suspected cause

No idea, maybe a corrupted download/install process?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
Mind showing some errors? It might have to do with Garuda

**Comment by Lucas559-noob** [comment]
make sure to change to right java version, if there is some old modpacks, try updating forge or idk what it use, updating forge fixed some old modpacks problems

**Comment by NekoTheWeird** [comment]
> Mind showing some errors? It might have to do with Garuda

What errors exactly? Some logs?

**Comment by Samisafool** [comment]
Yes. Use hastebin, don't paste it here

**Comment by NekoTheWeird** [comment]
### Ok guys i heavily apologize, the problem is resolved.
The problem was in the Java version. _(Maybe the openJDK 17 doesnt like LInux?)_
**Changed it do Liberica Full JDK8 and everything works as it should.**

> make sure to change to right java version, if there is some old modpacks, try updating forge or idk what it use, updating forge fixed some old modpacks problems

Yes you were right. Man why didnt i think of that, im so stupid lol.
Thank you very much.
