### ISSUE TITLE
Support for other account types (Mojang, Offline, MCLeaks, others) 

### ISSUE THREAD

**Issue by AfoninZ** [AfoninZ/MultiMC5-Cracked#17]
Currently this launcher just asks for the username every time you start the game. Furthermore, it uses the same UUID regardless of the username. This causes issues with LAN worlds, if both players use this launcher.

Multiple Minecraft launchers with offline functionality (like TLauncher) have support for alternative account types (Mojang account, "offline" account, and accounts from alternative login systems like Ely.by). If implemented, this would allow for a seamless experience much like with a legitimate Mojang account.

**Comment by charizardavi** [comment]
If you could login with ely.by, would the skins show?

**Comment by Sebastian-byte** [comment]
We could close this issue with #31

**Comment by AfoninZ** [comment]
Support for Ely.by implemented in #31, closing the issue.
