### ISSUE TITLE
[Non-game related] Is hosting the binaries on somewhere that supports resuming possible?

### ISSUE THREAD

**Issue by Ben1701A** [AfoninZ/MultiMC5-Cracked#171]
### Role

I use alt accounts on a cracked server in replacement of /back being disabled.

### Suggestion

I would like the download link to be resumable (HTTP 206 Partial Content).

### Benefit

so that people on rough network conditions are able to multi-thread their downloads, as well as resume when their connection gets reset.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Also, the site hosting the binaries doesn't report file size, so my download manager is unable to display progress.

**Comment by Ka1dz0** [comment]
Dude... the file weighs 13mb,what are the alternative download links?
As a last resort, use IDM (internet download manager)

**Comment by Ben1701A** [comment]
Yeah. And it takes 20m at best to get 50mbytes of data in my location.
Sometimes the connection drops out entirely.

**Comment by AndreVuillemot** [comment]
>Is hosting the binaries on somewhere that supports resuming possible?

No, lol. It's more of GitHub side of things.

**Comment by Ben1701A** [comment]
> No, lol. It's more of GitHub side of things.

Aw, ok.
Thanks, I think I'll close this issue then.
