### ISSUE TITLE
cmake errors when building on Alpine

### ISSUE THREAD

**Issue by MrVeink** [AfoninZ/MultiMC5-Cracked#176]
### Operating System

Linux

### Description of bug

```sh
$ cmake -DCMAKE_INSTALL_PREFIX=../install ../src
-- Git commit: 4afe2466fd5639bf8a03bfb866c070e705420d86
-- Git refspec: refs/heads/develop
CMake Error at CMakeLists.txt:239 (add_subdirectory):
  The source directory

    /home/<user>/.mmc/src/libraries/libnbtplusplus

  does not contain a CMakeLists.txt file.


/home/<user>/.mmc/src/cmake
CMake Error at CMakeLists.txt:247 (add_subdirectory):
  The source directory

    /home/<user>/.mmc/src/libraries/quazip

  does not contain a CMakeLists.txt file.


/home/<user>/.mmc/src/cmake
From /home/<user>/.mmc/src/launcher/testdata to /home/<user>/.mmc/build/launcher/data
From /home/<user>/.mmc/src/launcher/updater/testdata to /home/<user>/.mmc/build/launcher/data
From /home/<user>/.mmc/src/launcher/updater/testdata to /home/<user>/.mmc/build/launcher/data
From /home/<user>/.mmc/src/launcher/minecraft/testdata to /home/<user>/.mmc/build/launcher/data
From /home/<user>/.mmc/src/launcher/testdata to /home/<user>/.mmc/build/launcher/data
-- Configuring incomplete, errors occurred!
```

Running Alpine Linux v3.15. 

### Steps to reproduce

Using Alpine Linux:
1) `mkdir .mmc`
2) `mkdir build && mkdir install`
3) `git clone https://github.com/AfoninZ/MultiMC5-Cracked.git src && cd build`
4) `cmake -DCMAKE_INSTALL_PREFIX=../install ../src`

### Suspected cause

I am suspecting this is distro related, but I'm not sure.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
Read https://github.com/AfoninZ/MultiMC5-Cracked/blob/develop/BUILD.md

**Comment by MrVeink** [comment]
> Read https://github.com/AfoninZ/MultiMC5-Cracked/blob/develop/BUILD.md

I am following it...

**Comment by Samisafool** [comment]
You forgot to clone using `--recursive`.

```
git submodule init
git submodule update
cmake -DCMAKE_INSTALL_PREFIX=../install ../src
```

**Comment by MrVeink** [comment]
> You forgot to clone using `--recursive`.
> 
> ```
> git submodule init
> git submodule update
> cmake -DCMAKE_INSTALL_PREFIX=../install ../src
> ```

Ah, my bad. Thanks!
