### ISSUE TITLE
Removing the MultiMC name from the UI

### ISSUE THREAD

**Issue by AfoninZ** [AfoninZ/MultiMC5-Cracked#18]
This project was always named "MultiMC Cracked" because it, well, was a fork of MultiMC. However, MultiMC's Apache license does not allow to use the original MultiMC name for its forks (from the original README, `This means people must take the time to go through the source code and remove all references to "MultiMC", including but not limited to the project icon and the title of windows, (no MultiMC-fork in the title)`.

Despite not having any problems with the MultiMC developer team, using the original name for this project is still a violation of the original license. Oh, and also people may have problems with this rarely updated, not really tested fork and report the problems to the original developers. To resolve this, it would be the best to strip this launcher of any visible mentions of MultiMC, except for the credits to its developers.

**Comment by Dakkaron** [comment]
How about the Github repo? Is this allowed to be called MultiMC-Cracked?

**Comment by AfoninZ** [comment]
It can be renamed, but I've heard it can lead to some problems - also, I think that's how people initially found this repository.

**Comment by Dakkaron** [comment]
That's what I thought... Renaming the repo would be troublesome. The question is just if the Apache license applies to the product only, or also to surrounding material like the repo name.

**Comment by Sebastian-byte** [comment]
We can start by [this](https://github.com/MultiMC/MultiMC5/pull/3606) pull request, it already changes most definitions of MultiMC to launcher, but doesn't compiles yet.

**Comment by AfoninZ** [comment]
I've seen several MultiMC contributors discuss our fork in not-so-positive light, but I agree we need to rebrand and detach so nobody grinds their gears and causing any tantrums by uploading a crash log with a different version string. Any suggestions for the new name?

**Comment by Sebastian-byte** [comment]
> I've seen several MultiMC contributors discuss our fork in not-so-positive light, but I agree we need to rebrand and detach so nobody grinds their gears and causing any tantrums by uploading a crash log with a different version string. Any suggestions for the new name? @Sebastian-byte @Dakkaron if you're not busy oc

I'm not sure, however debranding should be a lot easier now.

**Comment by Darthagnon** [comment]
What about ```UltimMC``` (anagram)? Or ```Meinkraft`` or ```Meincrack```? Or ```MineKraken Launcher```; could be a good "nautical" reference, as well as relevant to this being a fork/branch of the original, and supporting multiple account types (like octopus legs)?

**Comment by Samisaprogrammer** [comment]
+1 for UltimMC

**Comment by Slddev** [comment]
+1 for UltimMC

**Comment by SlimF** [comment]
CrackMC?

**Comment by Samisaprogrammer** [comment]
> CrackMC?

Kinda sounds like a launcher which also happens to be a minecraft drug marketplace

**Comment by SlimF** [comment]
> 
> 
> > CrackMC?
> 
> Kinda sounds like a launcher which also happens to be a minecraft drug marketplace

You're saying it as if it's a bad thing

**Comment by TopologicallySpeaking** [comment]
The original README should eventually be updated as well. I point this out because I almost contacted the MultiMC devs on Discord by accident. If I wasn't logged out, I would probably not have realized that was the wrong Discord server.

**Comment by Samisafool** [comment]
> The original README should eventually be updated as well. I point this out because I almost contacted the MultiMC devs on Discord by accident. If I wasn't logged out, I would probably not have realized that was the wrong Discord server.

Yeah I made #83 for that

**Comment by maximmasterr** [comment]
I changed launcher name to UltimMC

**Comment by Samisafool** [comment]
Build artifacts still have "MultiMC" folder in them.

**Comment by maximmasterr** [comment]
Well, i fix that after repository rename

**Comment by Samisafool** [comment]
That's fixed too... I think this should be closed?

**Comment by Sebastian-byte** [comment]
Yes

**Comment by Samisafool** [comment]
Probably unpin this, @Sebastian-byte ?

**Comment by Slddev** [comment]
Why is this still not unpinned?

**Comment by Sebastian-byte** [comment]
Because we probably want to people be aware that there was a debranding process.

**Comment by Sebastian-byte** [comment]
@AfoninZ I consider that you should rename this repository as well.

**Comment by JulekSTN** [comment]
@Sebastian-byte you are right.

**Comment by OskarZyg** [comment]
Why are all of you worrying about this license violation when the entire repository is dedicated to intentionally violating Mojangs EULA?

**Comment by AfoninZ** [comment]
IMO the "no MultiMC name" license is justified: there have been many buggy unmaintained forks keeping the original name, leading users to mail support of original MultiMC when in reality it's the fork that has a problem. I think MMC developers are cool people doing cool things and they deserve better than doing tech support for sketchy forks.

**Comment by griffi-gh** [comment]
github setups redirects so the repo should be safe to rename.
but MultiMC-cracked probably has better SEO
