### ISSUE TITLE
NOISSUE Add offline mode name choices

### ISSUE THREAD

**Issue by PibePlayer** [AfoninZ/MultiMC5-Cracked#20]
to avoid the need to type the name each time you run, there is a branch for that

**Comment by PibePlayer** [comment]
Had to learn QT to "fix" it myself #23

**Comment by emmanoel1** [comment]
> Had to learn QT to "fix" it myself #23

how you fixed bro?

**Comment by AfoninZ** [comment]
Implemented in the newest comment, soon merged into master
