### ISSUE TITLE
Add support for starting the game without internet connection

### ISSUE THREAD

**Issue by PibePlayer** [AfoninZ/MultiMC5-Cracked#21]
It always fails if I don't have internet since it checks if it's up to date

**Comment by PibePlayer** [comment]
Found that if I change
`process->appendStep(new Update(pptr, Net::Mode::Online));` in [https://github.com/AfoninZ/MultiMC5-Cracked/blob/develop/api/logic/minecraft/MinecraftInstance.cpp](MinecraftInstance.cpp) at line 847 with
`process->appendStep(new Update(pptr, Net::Mode::Offline));`
I'm able to play it offline, needs more testing for repercussions (Unable to update, unable to access servers from the game, didn't test anything yet)

**Comment by Darthagnon** [comment]
I'm interested in offline play, too. Need to test the latest CI builds, as I don't remember having any trouble about a year ago playing offline with some homebrew builds.

**Comment by PibePlayer** [comment]
> I'm interested in offline play, too. Need to test the latest CI builds, as I don't remember having any trouble about a year ago playing offline with some homebrew builds.

It still works, but it gives an error if you didn't play the first time online, since it needs to download some things first, so I would need to add a counter of launches and a different launch mode for Offline Play

**Comment by maximmasterr** [comment]
Should be fixed with 04f580b
