### ISSUE TITLE
How do I login?

### ISSUE THREAD

**Issue by charizardavi** [AfoninZ/MultiMC5-Cracked#22]
I tried putting random usernames and passwords, yet I can't log in. How do I log in?

**Comment by charizardavi** [comment]
When I installed it, it asked me if I wanted to update it so I did. Was that the problem?

**Comment by charizardavi** [comment]
Ah yes now it works. I used the old version

**Comment by Dakkaron** [comment]
I believe the update function still fetches the original multimc. So if you update, the crack is gone.
