### ISSUE TITLE
Offline version command line

### ISSUE THREAD

**Issue by IronRevelation** [AfoninZ/MultiMC5-Cracked#27]
It would be awsome to be able to start an offline mode instance using the terminal (right now it's only possible using an account)

**Comment by AfoninZ** [comment]
Now possible with **feature-accounts** branch as "cracked mode" accounts can be created. Instances are launched just like in original MultiMC: `./MultiMC -l instance_name`

**Comment by AfoninZ** [comment]
The branch will most likely be merged with **master** soon, so the feature will be available in the precompiled binaries as well.
