### ISSUE TITLE
can you build release MultiMC5-Cracked version a months or six please ?

### ISSUE THREAD

**Issue by DarkFrost89** [AfoninZ/MultiMC5-Cracked#29]
firstly thank you make for MultiMC5-Cracked version of minecraft.
but ı have problem, ı dont have any java or c++ compile ability and ı dont know how to use Qt software
can you build release MultiMC5-Cracked version a months or six, because ı didnt build it :(

**Comment by infinitygamer404** [comment]
Can't you download the build from the google drive link that's in the README ?

**Comment by Sebastian-byte** [comment]
You can download using links in README
