### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mirkokral** [AfoninZ/MultiMC5-Cracked#34]
os: Fedora 34

LOG:
MultiMC version: 0.6.12-develop-2100

Minecraft folder is:
/home/mirko/MultiMC/instances/b1.7.3/.minecraft

Java path is:
/usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.fc34.x86_64/bin/java

Checking Java version...
Java is version 11.0.11, using 64-bit architecture, from Red Hat, Inc..

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Intel Corporation HD Graphics 630 (rev 04)

Subsystem: Lenovo Device 39fc

Kernel driver in use: i915

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.2

Main Class:
  

Native path:
  /home/mirko/MultiMC/instances/b1.7.3/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  /home/mirko/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/mirko/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/mirko/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/mirko/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/mirko/MultiMC/libraries/com/mojang/minecraft/b1.7.3/minecraft-b1.7.3-client.jar

Native libraries:
  /home/mirko/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/mirko/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 32857

Using onesix launcher.

Launching with applet wrapper...
16 achievements
151 recipes
Setting user: Player, -
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with code 127.

**Comment by AfoninZ** [comment]
This behavior is also present in the original MultiMC launcher. It's probably a Java version issue with old Minecraft versions. Installing an older Java package helped some users: https://github.com/MultiMC/MultiMC5/issues/3386
