### ISSUE TITLE
Minor - Better CI usage

### ISSUE THREAD

**Issue by AfoninZ** [AfoninZ/MultiMC5-Cracked#36]
Just a minor problem to discuss, do we need CI builds to run on every commit to `develop` or would builds for incoming PRs be sufficient? I've noticed most commits to `develop` are minor tweaks, readme changes and fixes unrelated to the actual code, yet they all produce CI builds. Asking @Sebastian-byte for suggestions on this one because I'm not sure if we only want CI on PRs or CI on pushes to specific branches that are not `develop`

**Comment by Sebastian-byte** [comment]
Currently the CI is set to run in every commit, every time we invoke it and every pull request to `develop`, we could disable build on commit.

**Comment by Sebastian-byte** [comment]
nightly.link ignores manual builds, so the nightly link is very outdated.
