### ISSUE TITLE
Unable to play multiplayer

### ISSUE THREAD

**Issue by ZeusMods** [AfoninZ/MultiMC5-Cracked#39]
Hello, it seems after this PR https://github.com/AfoninZ/MultiMC5-Cracked/pull/31
I am unable to play multiplayer and gives an error
`Failed to log in: The auth servers are not reachable. Please try again`

**Comment by ZeusMods** [comment]
Also, it can give this `Failed to verify username`

**Comment by maximmasterr** [comment]
Could you send logs and account type you are using, also try to create new local account

**Comment by ZeusMods** [comment]
@maximmasterr Hello, I just resolved the issue right now. It was on my side. Sorry for making the issue. Have a nice day!

**Comment by ZeusMods** [comment]
I would like to ask does Ely.by auth works for you?

**Comment by maximmasterr** [comment]
Yes, according to my tests two different ely.by accounts can play with each other over lan and hamachi, skin system works too
