### ISSUE TITLE
Recent MultiMC download requiring account to play.

### ISSUE THREAD

**Issue by TheUnknownOriginal** [AfoninZ/MultiMC5-Cracked#40]
Hi, so I downloaded another version of MultiMC a week ago and I used to be able to play without the need for mojang account when I launch an instance. But after I clicked update on the MultiMC update thing it now requires me to use a Mojang account. So i deleted the whole Multimc folder and redownloaded the MultiMC cracked from the google drive in readme but now it keeps asking me for an account to be able to play.

**Comment by Qpac-x** [comment]
go to settings -> accounts -> add account, and then you can pick between ely.by and local (cracked) both are cracked but ely.by lets you use skins, hope this helps.

**Comment by TheUnknownOriginal** [comment]
Thanks, I went ahead and created a ely.by account and it works!
