### ISSUE TITLE
Can't open Linux x64 tar.gz

### ISSUE THREAD

**Issue by Juane20** [AfoninZ/MultiMC5-Cracked#43]
Hi. I'm trying to open the program in Ubuntu 18.04 Bionic, and i can't. I extracted with `tar -zxvf` and then `cd MultiMC` and `./MultiMC`. And i get this error:
./MultiMC 
MultiMC Dir: /home/casa2/MultiMC
No missing dependencies found.
/home/casa2/MultiMC/bin/MultiMC: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /home/casa2/MultiMC/bin/MultiMC)
/home/casa2/MultiMC/bin/MultiMC: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /home/casa2/MultiMC/bin/libMultiMC_gui.so)
/home/casa2/MultiMC/bin/MultiMC: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /home/casa2/MultiMC/bin/libMultiMC_rainbow.so)
/home/casa2/MultiMC/bin/MultiMC: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/casa2/MultiMC/bin/libMultiMC_rainbow.so)
/home/casa2/MultiMC/bin/MultiMC: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /home/casa2/MultiMC/bin/libMultiMC_iconfix.so)
/home/casa2/MultiMC/bin/MultiMC: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /home/casa2/MultiMC/bin/libMultiMC_logic.so)
/home/casa2/MultiMC/bin/MultiMC: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /home/casa2/MultiMC/bin/libMultiMC_quazip.so)
/home/casa2/MultiMC/bin/MultiMC: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/casa2/MultiMC/bin/libMultiMC_nbt++.so)

I installed qt5-default but i can't get it works.
Thanks!

**Comment by Sebastian-byte** [comment]
This also happens on the MultiMC (not cracked) launcher

**Comment by Juane20** [comment]
> This also happens on the MultiMC (not cracked) launcher?

I installed the .deb package of the official launcher and it works fine. But the cracked version doesn't work yet.

**Comment by Sebastian-byte** [comment]
.deb package != generic, try using the generic no cracked one.

**Comment by Juane20** [comment]
So, the tar.gz file of the official MultiMC launcher?

**Comment by Sebastian-byte** [comment]
Yes

**Comment by Juane20** [comment]
Ok ok, thank you! I'll try it right now

**Comment by Juane20** [comment]
I did the same process with the tar.gz file of official MultiMC and it works fine, i don't understand why

**Comment by PibePlayer** [comment]
@Sebastian-byte If I'm not wrong this problem is caused since it's built in Ubuntu-lastest (20.04) wich has Qt 5.12 and was built against it, while Ubuntu bionic has Qt 5.9, and is unable to find 5.12 libraries. The problem should be solved changing `ubuntu-lastest` to `ubuntu-18.04` on [main.yml#11](https://github.com/AfoninZ/MultiMC5-Cracked/blob/c647ddb1245286a25dc461b6b3a8bff0954da7ac/.github/workflows/main.yml#L11).
I'm testing that on my repo: [CI Ubuntu 18.04](https://github.com/PibePlayer/MultiMC5-Cracked/actions/runs/988163745)

**Comment by Sebastian-byte** [comment]
Shouldn't have problems since Qt is backwards compatible.

**Comment by PibePlayer** [comment]
@Juane20, Please try this build: [MultiMC5-Cracked Ubuntu18.04 Build](https://github.com/PibePlayer/MultiMC5-Cracked/suites/3128921945/artifacts/71756823)

**Comment by Juane20** [comment]
> @Juane20, Please try this build: [MultiMC5-Cracked Ubuntu 18.04 Build](https://github.com/PibePlayer/MultiMC5-Cracked/suites/3128921945/artifacts/71756823)

Really thanks! It works fine. Thanks both!

**Comment by Juane20** [comment]
I'm sorry. It's the cracked version? Because i can't add an account.

**Comment by Juane20** [comment]
> I'm sorry. It's the cracked version? Because i can't add an account.

Sorry. I created an instance and when I started it asked me an user. Thanks again.
