### ISSUE TITLE
[BUG] It asks for a Java Account

### ISSUE THREAD

**Issue by Vortex-sky** [AfoninZ/MultiMC5-Cracked#47]
### Operating System

Windows

### Description of bug

Newest Windows Pre-Built Binary version still asks for a Java account, despite me not updating MultiMC

### Steps to reproduce

1. Download the Prebuilt Windows binary
2. Use WinRAR to open extract the .zip
3. Open MultiMC.exe
4. Download the latest Java version from Oracle's site
5. Setup the javaw.exe
6. Launch any version (i used 1.16.5)
7. Bug

### Suspected cause

I suspect that the newest version is broken

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Vortex-sky** [comment]
Also, the error screen:
![20210705_162822](https://user-images.githubusercontent.com/80209203/124482453-fa1bae00-ddb1-11eb-99b2-b8c091ed46ce.jpg)

**Comment by AfoninZ** [comment]
Add the account. When you open the menu, it actually provides other options that include an offline account (aka username + any password)

**Comment by Vortex-sky** [comment]
Alr thx
