### ISSUE TITLE
"Failed to connect to server: Disconnected"

### ISSUE THREAD

**Issue by MineRock** [AfoninZ/MultiMC5-Cracked#48]
### Operating System

Windows

### Description of bug

I tried this in 2 different PCs with both the Ely.by and local system. Both times, multiplayer didn't work with the following error: "Failed to connect to server: Disconnected".

### Steps to reproduce

- Install MultiMC from the nightly build
- Make new instance
- Try to play multiplayer
- <Error>

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
This seems like a problem with your mods, you can reproduce this in a instance without mods?

**Comment by MineRock** [comment]
I have no mods. It was tested with a vanilla instance of 1.17.1 and 1.16.5 (I checked in both(

**Comment by Sebastian-byte** [comment]
This is a game bug and this issue got opened in the upstream repository.

**Comment by maximmasterr** [comment]
Are you trying to connect from local instance to elyby

**Comment by MineRock** [comment]
i don't understand what you mean, sorry.

**Comment by AndreVuillemot160** [comment]
He means did your local account you made tried connect to elyby one.

**Comment by MineRock** [comment]
No

**Comment by MineRock** [comment]
ah okay. both the ely.by accounts and local accounts were named "MineRockerRepacks". switching local account to another name worked in multiplayer. closing the issue.
