### ISSUE TITLE
Direct Server Joining doesn't work

### ISSUE THREAD

**Issue by RaXorX** [AfoninZ/MultiMC5-Cracked#49]
### Operating System

Windows

### Description of bug

Setting a default server to Join on startup in the miscellanous settings or using the Join button from the server tab in edit instance mode, either of those crashes minecraft while launching the same server after the game loads work fine.

### Steps to reproduce

Assign a server as a default to join right on launch and launch the instance or add a server from the servers tab within the instance setting and click on Join for that server. Minecraft starts and crashes.

### Suspected cause

The server does has mods and the client too, the ones that are required to join the server. Once the instance launches can join the server fine but otherwise not.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
This seems like a upstream problem.

**Comment by Sebastian-byte** [comment]
This is a game bug and this issue got opened in the upstream repository.
