### ISSUE TITLE
Assign Default account to an instance

### ISSUE THREAD

**Issue by RaXorX** [AfoninZ/MultiMC5-Cracked#50]
### Role

Multiple Account instancing

### Suggestion

Assign default account to an instance.

### Benefit

Easier to handle account management per instance, otherwise you need to change the account in menu first before starting an instance.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Sebastian-byte** [comment]
You must request this feature to the upstream (non-cracked) repository.
