### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by carlosgalves** [AfoninZ/MultiMC5-Cracked#51]
### Operating System

Linux

### Description of bug

When I try executing the script it gives me a "Permission denied" error. I also tried installing with a package installer and I get the same issue.

### Steps to reproduce

After extracting the file I opened its directory and executed `./MultiMC` in the terminal.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
This is clearly a permission problem, try running `chmod +x ./multimc` and try again.

**Comment by carlosgalves** [comment]
That solved it. Thank you!
