### ISSUE TITLE
Update macOS builds + add macOS build task to CI, if possible

### ISSUE THREAD

**Issue by AfoninZ** [AfoninZ/MultiMC5-Cracked#52]
### Role

Right now the macOS build is kind of outdated, not containing the features of Ely.by support, account saving and other nice things.

### Suggestion

Update the Mac builds and, if possible, add macOS build tasks to CI so the builds would always stay up to date.

### Benefit

Would allow Mac users to enjoy the benefits of this launcher

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Sebastian-byte** [comment]
https://github.com/kaanyalova/MultiMC5-Cracked did some advancement in this.
