### ISSUE TITLE
Launcher not working

### ISSUE THREAD

**Issue by KarPro714** [AfoninZ/MultiMC5-Cracked#54]
When I run BetterMinecraft offline, it shows this error- https://paste.ee/p/Du71n
But, when I run Stoneblock 2, this one appears instead - https://paste.ee/p/QTsSZ

**Comment by KarPro714** [comment]
However, vanilla Minecraft works perfectly.

**Comment by KarPro714** [comment]
Of all the the different ones I've tried only 1.18 experimental snapshots have worked

**Comment by AfoninZ** [comment]
Have you tried using older Java versions like good old Java 8? It's 1.17+ that needs Java 16 to work.

**Comment by KarPro714** [comment]
Actually, it showed a different error when I used Java 8(it was my actual comment before I edited it)
https://paste.ee/p/cyTxG

**Comment by KarPro714** [comment]
@AfoninZ
