### ISSUE TITLE
How To Use or play?

### ISSUE THREAD

**Issue by prohassanwaqas** [AfoninZ/MultiMC5-Cracked#57]
It seems to be the case that this version still requires for a mojang account, but it should not be the case right?
where is the information mentioned for how to use this?

**Comment by AndreVuillemot160** [comment]
Greetings, create an local account. With your username in email field, and write random password.
?????
PROFIT

**Comment by prohassanwaqas** [comment]
I don't know what you mean by local account, I don't see no option on multi MC menu as such. A little more detail would suffice

**Comment by prohassanwaqas** [comment]
Oh wait..... It was bugged.... Now its showing me the local option... Weird
