### ISSUE TITLE
Cant change Skin

### ISSUE THREAD

**Issue by ANDREWJOHN509** [AfoninZ/MultiMC5-Cracked#63]
### Operating System

Windows

### Description of bug

Hello,I was today playing MultiMC (Cracked) and I just figured out I cant change the skin, I even looked into the Bin files and there wasnt anything. Can somebody tell me how to change the Skin in MultiMC Cracked? Thank you!

### Steps to reproduce

Please help

### Suspected cause

I d k

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by AfoninZ** [comment]
For now we don't support changing your own skin on "local" accounts. However, for that we have Ely.by skin system implemented - check it out. You can make an account there and then login with Ely.by, so you can use the skin you've uploaded on the website. You also can play on LAN with other Ely users.

**Comment by ANDREWJOHN509** [comment]
Just noticed it now! Thanks!

Am Fr., 13. Aug. 2021 um 21:59 Uhr schrieb Zakhar Afonin <
***@***.***>:

**Comment by ANDREWJOHN509** [comment]
Thanks!

**Comment by MavisCelus19201** [comment]
I have something similar, one instance comes with a skinfix and it DID change the skin, but I don't know how to change it from there, this is with an offline account, not sure where skin files are located so I might try making an Ely.by skin, assuming those work for beta versions.
