### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by LuckOrLag** [AfoninZ/MultiMC5-Cracked#65]
### Operating System

Windows

### Description of bug

It tells me I need a minecraft account, I typed random stuff but it doesn't work
![Capture](https://user-images.githubusercontent.com/87932649/130288256-95824112-13a1-4efa-9198-7e6ecefbba0d.PNG)

### Steps to reproduce

I installed the 0.6.11 and copy pasted the crack.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by rexmightlag** [comment]
Where did you download the launcher from? Download the one from this repo (pre-built link is available on the main repo page), extract it to a new folder and try running.

**Comment by LuckOrLag** [comment]
> Where did you download the launcher from? Download the one from this repo (pre-built link is available on the main repo page), extract it to a new folder and try running.
> 
> Edit: Also, there is no separate "crack" or anything that you need to paste, the launcher just works standalone.

ok ty
