### ISSUE TITLE
Pre-Built Link Borken

### ISSUE THREAD

**Issue by Bob0111** [AfoninZ/MultiMC5-Cracked#66]
### Operating System

Linux

### Description of bug

I cannot download the cracked version of the launcher from the link you provide.

### Steps to reproduce

Download it from the link.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by AndreVuillemot160** [comment]
Eh, these links are still working for me personally.

**Comment by Bob0111** [comment]
The download link doesn't download the cracked version. Instead, it downloads the original version. I download the lin64 version.
