### ISSUE TITLE
The download link doesn't download the cracked version. Instead, it downloads the original version. I download the lin64 version.

### ISSUE THREAD

**Issue by Bob0111** [AfoninZ/MultiMC5-Cracked#68]
The download link doesn't download the cracked version. Instead, it downloads the ubcracked version. I download the lin64 version.

_Originally posted by @Bob0111 in https://github.com/AfoninZ/MultiMC5-Cracked/issues/66#issuecomment-913440494_

**Comment by AndreVuillemot160** [comment]
Dude, it is linking to the cracked version already. I tried yesterday and everything working as intended.

**Comment by AndreVuillemot160** [comment]
When program asks your email and password. As email write your username, and then put random password. Profit.

**Comment by Bob0111** [comment]
Thank you four your reply.

**Comment by Bob0111** [comment]
The older version doesn't require this. So I really didn't know that. Thank you again!

**Comment by AndreVuillemot160** [comment]
You are welcome, I guess I need to write a tutorial on how to use cracked launcher xD

**Comment by Bob0111** [comment]
Totally agree. By the way, any idea to upgrade? The development version on the upstream has already supported Microsoft account.

**Comment by AndreVuillemot160** [comment]
> Totally agree. By the way, any idea to upgrade? The development version on the upstream has already supported Microsoft account.

Eh, devs of cracked version are currently doing rebranding stuff. Probably after they are done they will push a new version.
