### ISSUE TITLE
How do i install it on linux?

### ISSUE THREAD

**Issue by L0oois** [AfoninZ/MultiMC5-Cracked#69]
hi, i'm new here and i don't know how to install the client on linux, i'm also new there. help me.

**Comment by Samisaprogrammer** [comment]
download the file, extract to a folder, and run.

**Comment by L0oois** [comment]
how do i run it?

**Comment by AndreVuillemot160** [comment]
Alright, noobie guide on how to run it.
Download the file for linux.
Unpack in your desired directory.
Go to the folder, and then run console and cd to the folder where unpacked multimc is.
`chmod +x MultiMC`
The command above makes MultiMC script executable and then run it with
`./MultiMC`
After you will run it set up it, and go to accounts setup.
Add your account, as email use your username and write any password.
???
PROFIT!

**Comment by L0oois** [comment]
Thank you, :dango:
