### ISSUE TITLE
My game is crashing on Windows 10.

### ISSUE THREAD

**Issue by yum13241** [AfoninZ/MultiMC5-Cracked#73]
What I expect:

I can play modded (Fabric) 1.16.5.

Actual behavior:

I can't, because it complains about me not using Java 16, when 1.16.5 uses Java 8.

Crash log:

https://paste.ee/p/1huQi.

**Comment by owcxe** [comment]
> What I expect:
> 
> I can play modded (Fabric) 1.16.5.
> 
> Actual behavior:
> 
> I can't, because it complains about me not using Java 16, when 1.16.5 uses Java 8.
> 
> Crash log:
> 
> https://paste.ee/p/1huQi.

You tried to setup java patch by yourself in the instance gui settings?

**Comment by Samisaprogrammer** [comment]
some mods might need 16.

**Comment by yum13241** [comment]
Lol, I looked in the crash log, tries to understand it, and it says that OneSix launcher wants Java 16, but1.16 needs Java 8.

**Comment by Samisaprogrammer** [comment]
1.16 works with java 16

**Comment by Samisaprogrammer** [comment]
im serious lol, hacks (fabric ones) can mess with mixins

**Comment by yum13241** [comment]
It works in my heavily modded 1.17.1 instance with a bit more mods. Around 70.

**Comment by Samisaprogrammer** [comment]
And? Does that pack have all the mods this does?

**Comment by yum13241** [comment]
> guys java 16+ will be the new library releases from Mojang it is not about multimc. multimc downloads the libraries from mojang servers.
> 
> good thing is you can install 2 version of java in same device and define each in every profile whatever you want. edit profile and see the java setting in every profile :)


I literally bothered to do that ever since I heard of https://adoptium.net and it's predecessor, https://adoptopenjdk.net bc apparently their builds are higher quality.
