### ISSUE TITLE
I am not able to sign in for some reason

### ISSUE THREAD

**Issue by abbernatorr** [AfoninZ/MultiMC5-Cracked#78]
### Description of bug

it has two options
add microsoft
add mojang
i tried add mojang and it says "Mojang authentication failed"
hope you can help
![Screenshot (41)](https://user-images.githubusercontent.com/92780141/137862996-ed4fc6ac-23c4-4b3b-9389-410f712493ba.png)

### Steps to reproduce

Go to account settings and do add mojang

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by maximmasterr** [comment]
Fixed, you can use latest version now
