### ISSUE TITLE
Local Accounts cannot be added.

### ISSUE THREAD

**Issue by Slddev** [AfoninZ/MultiMC5-Cracked#84]
### Operating System

Windows, Linux, MacOS

### Description of bug

Local or Ely.by accounts cannot be added. 

### Steps to reproduce

1. Go to manage accounts
2. Click Add Mojang
3. Click Local Account
4. Set your username in the email field.
5. Set a random password
6. Then press OK

### Suspected cause

Maybe a conflict when Microsoft Support was added.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
Hi guys! Is there any update on the issue?

**Comment by AndreVuillemot160** [comment]
Just wait.

**Comment by Kimapr** [comment]
Anyone knows the last commit that still works? i want to use this

**Comment by maximmasterr** [comment]
I guess this should work `04f580b0bc4f77b4fb4baab081bc2c356675e962`
Also i am pretty sure I will this issue fix it Today

**Comment by Samisafool** [comment]
this is last working https://github.com/AfoninZ/MultiMC5-Cracked/commit/9069e9c9d0b7951c310fdcc8bdc70ebc422a7634

**Comment by maximmasterr** [comment]
Well, ely.by login works now, local login works but very very very buggy, and to fix it i should write real http server. I will have free time on Wednesday or Thursday, so use ely.by or old version for now

**Comment by Samisafool** [comment]
Windows build fails

**Comment by leviska** [comment]
Can I get some older build for windows, that works, if it exists?👀

**Comment by leviska** [comment]
It doesn't work for me and my friend :(

https://user-images.githubusercontent.com/14099557/139720899-301f6db3-2c9e-43a7-aab7-1d3a63cf22c3.mp4

**Comment by Samisafool** [comment]
You need to make an ely by account (free)

**Comment by leviska** [comment]
Ooooohhhh, thanks... But I could still play on a regular offline-mode server, yes?

**Comment by Samisafool** [comment]
Yes

**Comment by L0oois** [comment]
I can't login to my ely.by account on linux. does this fix only work for windows?

**Comment by Samisafool** [comment]
Logged in fine for me... Sounds like a layer 8 error

**Comment by L0oois** [comment]
> Logged in fine for me... Sounds like a layer 8 error

what does that means?

**Comment by Samisafool** [comment]
It means you should show how you're doing it

**Comment by Samisafool** [comment]
logged in on linux just fine

![image](https://user-images.githubusercontent.com/59611020/139722973-e24fd72f-f729-4bb9-8a28-750146187bc0.png)

**Comment by leviska** [comment]
try redownload the binary, it got updated just now

**Comment by L0oois** [comment]
oh ok

**Comment by Samisafool** [comment]
btw, the account adding button is still called "Add Mojang" but opens the normal popup

**Comment by L0oois** [comment]
yep now it works

**Comment by L0oois** [comment]
> try redownload the binary, it got updated just now

thank you

**Comment by AndreVuillemot160** [comment]
Nice, KDE @Samisafool

**Comment by Samisafool** [comment]
thanks?

**Comment by maximmasterr** [comment]
AND IT IS FIXED, at least for me it works. Please check fixes and report here.

**Comment by Samisafool** [comment]
It seems to be fine, but the type shows as "Mojang"

**Comment by lebestnoob** [comment]
> It seems to be fine, but the type shows as "Mojang"
> 
> ![image](https://user-images.githubusercontent.com/59611020/140404474-4c879bd1-52e1-477e-84c6-61ac0170515c.png)
> 
> Edit: I wonder if this can be fixed as well?
> 
> ![image](https://user-images.githubusercontent.com/59611020/140404408-4feaafe0-82b8-4a33-ab51-e6f43ec6b8e6.png)

I don't know if it still applies to this version, but in the older builds, before the debranding, I could add `-Dauthlibinjector.noShowServerName` to the java arguments to disable the localhost message in the menu screen.

**Comment by Samisafool** [comment]
Still works. Any chance of passing it by default to make it more pretty?

**Comment by maximmasterr** [comment]
Everything fixed, if you find any new bugs related to this, open new issue

> It seems to be fine, but the type shows as "Mojang"
Fixed

> Still works. Any chance of passing it by default to make it more pretty?
Nope, i think we shoul display this, it helps to understand what provider this  instance for, but we should add note about option how to disable this to README.

**Comment by Samisafool** [comment]
I'll make a PR that fixes the README. The last one got rejected because I was dumb. (A *fool*, if you will)
