### ISSUE TITLE
Auto-download Java feature.

### ISSUE THREAD

**Issue by zaphod77** [AfoninZ/MultiMC5-Cracked#86]
### Role

Playing without system java

### Suggestion

Option to auto-fetch mojang's java runtime for the version of minecraft you are trying to run.

### Benefit

So you can play minecraft without needing to download anything else first. :)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Many other launchers will autodownload not only minecraft, but also a standalone java runtime.

this is particularly important since older ones use java 8, which is usually what's installed for the system, but 1.17 and newer use java 16, which is usually NOT installed to the system.

The needed java runtimes can be downloaded from mojang/MS, the other launchers are doing it now. :)

**Comment by Sebastian-byte** [comment]
This will be implemented in the upstream soon, no need to implement it here, see @AndreVuillemot160 response.
