### ISSUE TITLE
Remove mojang name from account screen

### ISSUE THREAD

**Issue by Samisafool** [AfoninZ/MultiMC5-Cracked#92]
### Operating System

Windows, macOS, Linux, Other

### Description of bug

The add account button is shown as "Add Mojang". It should be "Add account". Same for when auth fails.

### Steps to reproduce

Try to add an account.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Samisafool** [comment]
Alternatively, add buttons for each provider.

**Comment by Sebastian-byte** [comment]
Closed by #96
