### ISSUE TITLE
Adding Custom Versions (Like OptiFine)

### ISSUE THREAD

**Issue by DerpWerp** [AfoninZ/MultiMC5-Cracked#93]
### Role

I have a laggy minecraft

### Suggestion

Add the custom versions option

### Benefit

It would be more fun, and you can just make your own minecraft or install a different kind

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Some people (including me) have laggy PCs so their minecraft is laggy so you need to add custom versions so we can add special versions of minecraft like OptiFine to reduce lag or to create custom stuff.

**Comment by Samisafool** [comment]
Just use sodium+fabric if you have a laggy pc

**Comment by maximmasterr** [comment]
You can install optifine to any instance. [Instruction](https://github.com/MultiMC/Launcher/wiki/MultiMC-and-OptiFine)

**Comment by Samisafool** [comment]
You need the normal minecraft launcher for that

**Comment by maximmasterr** [comment]
No you don't, i have instance with  optifine, just add optifine as forge mod

**Comment by Samisafool** [comment]
That's with the help of a modloader, not vanilla + optifine

**Comment by maximmasterr** [comment]
Yes, and is there any problem with that? When i used my old laptop, i hadn't any problems with that

**Comment by Samisafool** [comment]
That's not a proper solution, since he wants more custom versions too, idk

**Comment by DerpWerp** [comment]
ok

**Comment by Slddev** [comment]
I got a way to add optifine to vanilla without any modloader. Use this: https://github.com/MMCInstances/OptifineInstances

**Comment by DerpWerp** [comment]
> I got a way to add optifine to vanilla without any modloader. Use this: https://github.com/MMCInstances/OptifineInstances
> 
> EDIT: For the "custom" versions, you can already do this. With the zip feature. If you know how to make those zips then it should be fine.

thanks, it works now!
