### ISSUE TITLE
the ely.by skin always turn into burger guy

### ISSUE THREAD

**Issue by PhongIzBruh** [AfoninZ/MultiMC5-Cracked#94]
### Description of bug

on older versions, the ely.by skin always turn to burger guy

### Steps to reproduce

Versions:
1.8.9 and older

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by maximmasterr** [comment]
Can you provide screenshot?

**Comment by Samisafool** [comment]
Burger guy?? Send pictures, this is the only burger guy i know of 
![image](https://user-images.githubusercontent.com/59611020/141068031-3c3164da-8f6a-49ca-8eed-73a8f1ba8cab.png)

**Comment by PhongIzBruh** [comment]
> Can you provide screenshot?

I cant now. I'll give you the screenshots later. Thx for replying to my bug report.

**Comment by PhongIzBruh** [comment]
> Can you provide screenshot?

couldn't provide screenshot so
![image_2021-11-10_145115](https://user-images.githubusercontent.com/94038951/141071985-da303c3b-1cc8-4166-8245-b666068beb5c.png)
![skin](https://user-images.githubusercontent.com/94038951/141072035-7fabb51d-25aa-4197-b397-170e664ed6e9.jpg)

**Comment by maximmasterr** [comment]
What is your username on ely by, and where do you test your skin?

**Comment by Samisafool** [comment]
skins sometimes glitch on servers, that's probably it. try singleplayer or different server

**Comment by PhongIzBruh** [comment]
my username is JustPhong but idk wut do u mean with "test"

**Comment by PhongIzBruh** [comment]
> skins sometimes glitch on servers, that's probably it. try singleplayer or different server

i used singleplayer

**Comment by maximmasterr** [comment]
The problem is that you use username JustPhong, and there is minecraft premium user with this name, so please change your username to unused

**Comment by PhongIzBruh** [comment]
> The problem is that you use username JustPhong, and there is minecraft premium user with this name, so please change your username to unused

ok thx rlly much

**Comment by Samisafool** [comment]
close the issue @PhongIzBruh

**Comment by PhongIzBruh** [comment]
> close the issue @PhongIzBruh

ok
