### ISSUE TITLE
Convert normal style custom version to multimc style version

### ISSUE THREAD

**Issue by PhongIzBruh** [AfoninZ/MultiMC5-Cracked#97]
### Role

I play custom pvp clients.

### Suggestion

Add a section in the new instance menu that convert normal version to multimc style version.

### Benefit

So users can use their custom version,

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Samisafool** [comment]
This is a very light fork of MultiMC. It won't be added here, but don't ask on the main repo.

**Comment by PhongIzBruh** [comment]
ok

> This is a very light fork of MultiMC. It won't be added here, but don't ask on the main repo.
